### PR TITLE
Updated backend to support public views at separate URL

### PR DESCRIPTION
**Pull request by ColeLRogers**
- Created new url for public views
- Updated get_record() to work with public views (there's an extra layer)
- Updated the context data to pass along the is_public boolean to the front end for button rendering
- Updated tests, added ProgramCertRecord factory

### CODE REVIEW

**Comment by mikix** [comment]
@marcotuts - quick product opinion on /records/programs/shared/{uuid} as the public URL? I don't have a strong opinion myself, but maybe you do?

**Comment by marcotuts** [comment]
url suggestion looks good to me. 👍

**Comment by ColeLRogers** [comment]
Added a new commit to allow non-logged in users to access public view. Could a reviewer take a look at this latest commit?

**Comment by dianakhuang** [comment]
👍 Nice job with the new mixin!

**Pull request merged**
