### PR TITLE
DE-1151:  add page url to Segment event.

### PR DESCRIPTION
**Pull request by brianhw**
Credentials Pull Request
---

Make sure that the following steps are done before rebasing/merging

  - [ ] Request a review if desired
  - [ ] Squash/Fixup your branch to one commit
  - Config/Dependency Changes (e.g. config files, scripts that are used for provisioning etc.)
    - [ ] Make sure you have updated [edx/configuration](https://github.com/edx/configuration) and [edx/devstack](https://github.com/edx/devstack) if necessary
    - [ ] Make sure the change builds successfully in a sandbox
  - UI Changes 
    - [ ] Consider other browsers (e.g. Firefox)
    - [ ] Check mobile view
    - [ ] Consider accessibility (e.g. Run aXe on the page)

### CODE REVIEW

**Comment by brianhw** [comment]
@jlajoie I tagged you on this since you authored the original Segment code.  I need to get hostname information sent to GA, and Segment uses the page URL to do this.  I did not test this in devstack.  Is there a recommended way to approach this -- configuring devstack or sandbox or stage?

**Comment by jlajoie** [comment]
> @jlajoie I tagged you on this since you authored the original Segment code. I need to get hostname information sent to GA, and Segment uses the page URL to do this. I did not test this in devstack. Is there a recommended way to approach this -- configuring devstack or sandbox or stage?

I recall just testing this in stage back in the day, but going to defer this to @schenedx and the master's team as they're the code owners for credentials.

**Comment by schenedx** [comment]
@brianhw I think once you get a green light to merge, you can just test on stage. Another way I would say to test is to write unit tests. I think that's possible here. Do you think so too?

**Comment by schenedx** [comment]
I'll try to monitor this on stage

**Pull request merged**
