### PR TITLE
feat: Added upgrade-requirements workflow

### PR DESCRIPTION
**Pull request by Jawayria**
JIRA: https://openedx.atlassian.net/browse/BOM-2598

### CODE REVIEW

**Review by mraarif — APPROVED** [review]

**Comment by mraarif** [comment]
@edx/edx-aperture please review the email address set for job failure notifications

**Comment by crice100** [comment]
Email address looks good (it matches our jenkins jobs: https://github.com/edx/jenkins-job-dsl/blob/master/testeng/jobs/upgradePythonRequirements.groovy)

**Comment by justinhynes** [comment]
@mraarif and/or @Jawayria I'm not terribly familiar with this ongoing work, sorry! Should we expect the alerting mechanism to be the same? We get alerts (through OpsGenie I believe) for new PRs opened up that notify us in Slack. I was wondering if there was any guidance or need to adjust any alerting from this change?

**Review by justinhynes — APPROVED** [review]

**Comment by mraarif** [comment]
@justinhynes this email (OpsGenie) will only alert the team in case an upgrade job fails, otherwise, it'd tag the team on newly created PR that should notify the team via Github notification

**Pull request merged**
