### PR TITLE
Docs Cleanup

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/ecommerce

**Comment by rlucioni** [comment]
@clintonb looks like docs aren't building automatically in this repo either. Were you able to fix that for edx/ecommerce? If so, this repo could probably use the same treatment.

**Comment by clintonb** [comment]
@rlucioni you fixed it with the webhook. I'll take care of that.

**Comment by clintonb** [comment]
@rlucioni correction: this was due to our not install requirements when building docs.

**Comment by rlucioni** [comment]
@clintonb cool, thanks for fixing this! I should have mentioned that I checked the webhook and saw it was already active.

**Pull request merged**
