### PR TITLE
Allow app to start when STATICFILES_STORAGE is undefined

### PR DESCRIPTION
**Pull request by rlucioni**
@e0d @maxrothman

FYI @zubair-arbi

### CODE REVIEW

**Comment by e0d** [comment]
Log that it's unavailable?

**Comment by rlucioni** [comment]
@e0d updated. Logging handlers aren't defined at this stage, so I'm using the `warnings` module instead of the root logger.

**Comment by e0d** [comment]
:+1:

**Comment by maxrothman** [comment]
FWIW `STATICFILES_STORAGE` should be defined when using file storage as well.

**Pull request merged**
