### PR TITLE
fix the NameError on aws s3 settings

### PR DESCRIPTION
**Pull request by zubair-arbi**
@awais786 @tasawernawaz @ahsan-ul-haq

### CODE REVIEW

**Comment by zubair-arbi** [comment]
@clintonb we have to define these variables somewhere. If these variables are not in `credentials.yml` file then we will get exception `NameError: name 'AWS_STORAGE_BUCKET_NAME' is not defined`.

**Comment by clintonb** [comment]
If they need to be in credentials.yml, make sure they are always there. I would much rather the app fail to start when settings are missing than discover we are using empty strings later in production.

**Comment by zubair-arbi** [comment]
Thanks for the feedback. I have already added these variables in config PR: https://github.com/edx/configuration/commit/e1ea1165c864361b726d9ce335b76a7b573d46ac
But just wanted to make sure if we need to suppress this error or not.

**Comment by clintonb** [comment]
No. Errors are a good thing when caught early. I actually want more of our apps to run startup checks and fail if data does not meet expectations. If you need the data in an existing sandbox, manually add it.

**Pull request closed without merging**
