### PR TITLE
feat: replace rest_framework_swagger with drf_yasg

### PR DESCRIPTION
**Pull request by NeOneSoft**
This PR was created following edx/upgrades#17 to switch django rest swagger to drf-yasg

### CODE REVIEW

**Comment by justinhynes** [comment]
@NeOneSoft Hey there! It looks like this PR has been open for some time without any of the needed changes. Should we keep this open?

**Comment by NeOneSoft** [comment]
Hi @justinhynes sorry about my delay, I haven't had the chance to check this in the last weeks. The drf_yasg library https://github.com/JoelLefkowitz/drf-yasg is now supporting Django 32 however I can't figure out the reason why some CI checks are failing since I used the same approach on other PR's.Could you help me we this repository please?.Thanks in advance!!

**Comment by NeOneSoft** [comment]
@justinhynes Of course !!! Thank you so much for your response and I'll be attending your comments!!!= D

**Comment by justinhynes** [comment]
Hey @NeOneSoft! Hoping this may be an easy one. I see that most of these tests are failing with the following error:
```
ModuleNotFoundError: No module named 'drf_yasg'
```

I was looking at the PR and can see that we're trying to add `drf-yasg` to the `INSTALLED_APPS` but I don't see the Python package added as a requirement. If we're adding a new requirement then you will need to add it to the `base.in` file here: https://github.com/eduNEXT/credentials/blob/ednx/edx_upgrade_swagger/requirements/base.in. Afterwards, I believe you will need to run `make upgrade` locally to make sure the requirements files get updated.

Maybe this was accidentally removed when the branch was getting fixed up with the latest changes?

**Comment by NeOneSoft** [comment]
Hey there@justinhynes !! Thank you so much for your support. I noticed that our credentials repo was not updated so I will closed this PR on behalf of https://github.com/edx/credentials/pull/1502 in which I followed your instructions to fix the issues mentioned. I'll keep attending your comments!! and thanks a lot

**Comment by edx-webhook** [comment]
@NeOneSoft Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/credentials&entry.867055334=https://github.com/edx/credentials/pull/1408&entry.1484655318=https://github.com/NeOneSoft&entry.752974735=2021-10-20+01:04&entry.1917517419=2021-12-15+19:50&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
