### PR TITLE
Show organization short name instead of name

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**
ECOM-3949
@awais786 @tasawernawaz please review

### CODE REVIEW

**Comment by awais786** [comment]
Please add a test case to make sure short name appears while rendering.

**Comment by awais786** [comment]
:+1:

**Comment by ahsan-ul-haq** [comment]
@clintonb @marcotuts please review.

**Comment by clintonb** [comment]
You don't need me to review this. Product makes the call.

**Comment by marcotuts** [comment]
:+1:  merge away. thanks

**Pull request merged**
