### PR TITLE
Removed dead SASS

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/ecommerce please review

**Comment by AlasdairSwan** [comment]
@clintonb this PR has a decent amount of overlap with PR #189

**Comment by clintonb** [comment]
@AlasdairSwan correct. They are layered.

**Comment by clintonb** [comment]
@edx/ecommerce please review

**Comment by clintonb** [comment]
This was merged as part of https://github.com/edx/credentials/pull/191.

**Pull request closed without merging**
