### PR TITLE
chore: Upgrade requirements

### PR DESCRIPTION
**Pull request by xitij2000**
Upgrades requirements to remove rest-condition. 

**JIRA tickets**: 
https://github.com/edx/upgrades/issues/2

**Dependencies**: None

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [OSPR-6106](https://openedx.atlassian.net/browse/OSPR-6106) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@xitij2000 Thank you for your contribution. Please let me know once this is ready.

**Comment by xitij2000** [comment]
@natabene  This is good to go from my side. It's just a dependency upgrade.

**Review by staubina — APPROVED** [review]

**Comment by edx-webhook** [comment]
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/credentials&entry.867055334=https://github.com/edx/credentials/pull/1376&entry.1484655318=https://github.com/xitij2000&entry.752974735=2021-10-05+09:07&entry.1917517419=2021-10-05+19:25&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
