### PR TITLE
Remove usages of OAUTH2_PROVIDER_URL, add BACKEND_SERVICE_EDX_OAUTH2_…

### PR DESCRIPTION
**Pull request by pwnage101**
…PROVIDER_URL

Replace with either of these alternatives, depending on how its used:

* BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL
* SOCIAL_AUTH_EDX_OAUTH2_URL_ROOT

Credentials Pull Request
---

Make sure that the following steps are done before rebasing/merging

  - [ ] Request a review if desired
  - [ ] Squash/Fixup your branch to one commit
  - Config/Dependency Changes (e.g. config files, scripts that are used for provisioning etc.)
    - [ ] Make sure you have updated [edx/configuration](https://github.com/edx/configuration) and [edx/devstack](https://github.com/edx/devstack) if necessary
    - [ ] Make sure the change builds successfully in a sandbox
  - UI Changes 
    - [ ] Consider other browsers (e.g. Firefox)
    - [ ] Check mobile view
    - [ ] Consider accessibility (e.g. Run aXe on the page)

### CODE REVIEW

**Comment by pwnage101** [comment]
related: https://github.com/edx/configuration/pull/4999

**Comment by pwnage101** [comment]
The test failures are expected due to the tests making use of credentials master, as opposed to my credentials PR branch.

**Comment by doctoryes** [comment]
Do you mean *configuration* master above? Or are you talking about the base branch into which you're merging this branch? Shouldn't the credentials unittests pass in a self-contained manner?

**Comment by pwnage101** [comment]
Ugh, this is the credentials PR isn't it...
I thought I was looking at the configuration PR.  Now I'm going to  parse the failure again and make a fix.

**Pull request merged**
