### PR TITLE
Add a default value for FILE_STORAGE_BACKEND

### PR DESCRIPTION
**Pull request by cpennington**
@maxrothman: Review?
@zubair-arbi: FYI
@jimabramson: FYI

### CODE REVIEW

**Comment by maxrothman** [comment]
👍🏼

**Comment by jimabramson** [comment]
@cpennington curious why this is not needed in base.py ?

**Comment by zubair-arbi** [comment]
@cpennington thanks for fixing this but shouldn't changes in the configuration are enough? where we are setting the variable `FILE_STORAGE_BACKEND`.
https://github.com/edx/configuration/pull/2758/files

**Comment by cpennington** [comment]
@jimabramson we need the default so that line that extracts the dict into `vars()` works. In base.py, or other configurations that aren't loading from YAML, they should be explicitly setting the variables that are embedded in this dict.

**Comment by cpennington** [comment]
@zubair-arbi if the configuration doesn't have it set (like right now, because the PR hasn't merged), the code shouldn't blow up.

**Comment by jimabramson** [comment]
@cpennington got it :+1:

**Comment by zubair-arbi** [comment]
@cpennington the other PR is ready. I can merge it now as the build have passed now. Do we still need this to be merged?

**Comment by cpennington** [comment]
@zubair-arbi yes, to make the code resilient to that configuration not being set.

**Comment by zubair-arbi** [comment]
@cpennington Ok. :+1:

**Comment by maxrothman** [comment]
@zubair-arbi Let's continue to wait to merge the other PR until we've tested a build.

**Comment by zubair-arbi** [comment]
@maxrothman Sorry about that as I have already merged it. If we will need so other configuration changes than we will do that in a separate PR.

**Comment by jimabramson** [comment]
is it still the plan to merge this one?  is further action required before merging?

**Pull request merged**
